name: upload-ghpages

on:
  push:
    branches: [ master ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - uses: whoan/docker-build-with-cache-action@v4
      with:
        image_name: smellman/tippecanoe
        image_tag: latest

    - name: extract xzy from mbtiles
      run: docker run --rm -v $(pwd):/working -w /working smellman/tippecanoe:latest tile-join -e zxy tokyo.mbtiles

    - name: push to gh-pages
      run: |
        rm -fr .git
        rm -fr tokyo.mbtiles
        git config --global user.name "Taro Matsuzawa"
        git config --global user.email "btm@tech.email.ne.jp"
        git init .
        touch .nojekyll
        git add .
        git commit --quiet -m "Deploy from Github Action"
        git push --force https://$GITHUB_ACTOR:${{ secrets.GITHUB_TOKEN }}@github.com/$GITHUB_REPOSITORY master:gh-pages > /dev/null 2>&1
