# This is a basic workflow to help you get started with Actions

name: upload-ghpages

# Controls when the action will run. Triggers the workflow on push or pull request 
# events but only for the master branch
on:
  push:
    branches: [ master ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2

    # Runs a single command using the runners shell
    - name: Pull docker image
      run: docker pull smellman/tippecanoe:latest

    - name: extract xzy
      run: |
        mkdir working
        docker run --rm -v $(pwd):/working -w /working smellman/tippecanoe:latest tile-join -e working/zxy tokyo.mbtiles
    # Runs a set of commands using the runners shell
    - name: push to gh-pages
      env:
        github_repos: 
      run: |
        cd working
        git config --global user.name "Taro Matsuzawa"
        git config --global user.email "btm@tech.email.ne.jp"
        git init .
        echo touch .nojekyll
        touch .nojekyll
        echo cp tile.json
        cp ../tile.json .
        echo git add .
        git add .
        echo git commit
        git commit --quiet -m "Deploy from Github Action"
        echo git push --force
        git push --force --quiet "https://${{ secrets.GITHUB_TOKEN }}@github.com/${{ GITHUB_REPOSITORY }}" master:gh-pages > /dev/null 2>&1
